services:
  app:
    build: .
    container_name: ${COMPOSE_PROJECT_NAME:-apdate}-app
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ./upload:/var/www/html/upload
      - ./application/logs:/var/www/html/application/logs
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_NAME=${DB_NAME:-apdate}
      - DB_USER=${DB_USER:-root}
      - DB_PASS=${DB_PASS:-root_password}
      - APP_ENV=${APP_ENV:-development}
      - CI_ENV=${CI_ENV:-development}
      - BASE_URL=${BASE_URL:-http://localhost:8080}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-apdatev2}
    depends_on:
      - db
    networks:
      - apdate-network

  db:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME:-apdate}-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-root_password}
      MYSQL_DATABASE: ${DB_NAME:-apdate}
      MYSQL_USER: ${DB_USER_NON_ROOT:-apdate_user}
      MYSQL_PASSWORD: ${DB_USER_PASS:-apdate_password}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./DB_APDATE.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASS:-root_password}"]
      timeout: 20s
      retries: 10
    networks:
      - apdate-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${COMPOSE_PROJECT_NAME:-apdate}-phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    environment:
      PMA_HOST: ${DB_HOST:-db}
      PMA_PORT: 3306
      PMA_USER: ${DB_USER:-root}
      PMA_PASSWORD: ${DB_PASS:-root_password}
    depends_on:
      - db
    networks:
      - apdate-network

volumes:
  mysql_data:

networks:
  apdate-network:
    driver: bridge
