[phases.setup]
nixPkgs = ['php81', 'php81Packages.composer', 'apache2']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = [
    'mkdir -p /tmp',
    'chmod 777 application/logs',
    'chmod 777 application/cache'
]

[start]
cmd = 'apache2-foreground'